version: '3'
services:
  server:
    build: ./part5
    container_name: server
    networks:
      - mynetwork
  proxy: 
    build: ./part6
    container_name: proxy
    ports:
      - "80:8080"
    depends_on:
      - server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge